In [66]:
import pandas as pd
import numpy as np
import openpyxl

In [67]:
#Converting and loading serve.xlsx to serve.csv
data_xls = pd.read_excel('serve.xlsx', 'Serve', index_col=None)

data_xls.to_csv('serve.csv', encoding='utf-8', index=False)


In [68]:
#loading serve.csv to serve_df
serve_df = pd.read_csv('serve.csv')
serve_df.head()

Amount   Tip  Gender Smoker  Day    Time  Partysize  Unnamed: 7  Unnamed: 8  \
0  16.99  1.01  Female     No  Sun  Dinner        2.0         NaN         NaN   
1  10.34  1.66    Male     No  Sun  Dinner        3.0         NaN         NaN   
2  21.01  3.50    Male     No  Sun  Dinner        3.0         NaN         NaN   
3  23.68  3.31     Mal     No  Sun  Dinner        2.0         NaN         NaN   
4  24.59  3.61  Female     No  Sun  Dinner        4.0         NaN         NaN   

   Unnamed: 9 Unnamed: 10  
0         NaN         NaN  
1         NaN         NaN  
2         NaN         NaN  
3         NaN         NaN  
4         NaN         NaN

In [69]:
#df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
serve_df = serve_df.loc[:, ~serve_df.columns.str.contains('^Unnamed')]

serve_df.head()

Amount   Tip  Gender Smoker  Day    Time  Partysize
0  16.99  1.01  Female     No  Sun  Dinner        2.0
1  10.34  1.66    Male     No  Sun  Dinner        3.0
2  21.01  3.50    Male     No  Sun  Dinner        3.0
3  23.68  3.31     Mal     No  Sun  Dinner        2.0
4  24.59  3.61  Female     No  Sun  Dinner        4.0

# Data Cleaning

In [70]:
serve_df.Day.unique()


array(['Sun', 'Sat', 'Thur', 'Fri', 'Friday', 'Thurs', 'San', nan, 'S',
       'Sn'], dtype=object)

In [71]:

#Changing day names to THU, FRI, SAT and SUN
serve_df["Day"] = serve_df["Day"].replace(["Sun"],"SUN")
serve_df["Day"] = serve_df["Day"].replace(["Sat"],"SAT")
serve_df["Day"] = serve_df["Day"].replace(["Thur"],"THU")
serve_df["Day"] = serve_df["Day"].replace(["Fri"],"FRI")
serve_df["Day"] = serve_df["Day"].replace(["Friday"],"FRI")
serve_df["Day"] = serve_df["Day"].replace(["Thurs"],"THU")

#Changing other values in day to Nan
serve_df["Day"] = serve_df["Day"].replace(["San"],np.NaN)
serve_df["Day"] = serve_df["Day"].replace(["S"],np.NaN)
serve_df["Day"] = serve_df["Day"].replace(["Sn"],np.NaN)

serve_df.Day.unique()

array(['SUN', 'SAT', 'THU', 'FRI', nan], dtype=object)

In [72]:
#Cleaning the gender column
serve_df.Gender.unique()

array(['Female', 'Male', 'Mal', 'F', 'M', 'Fe'], dtype=object)

In [73]:
serve_df["Day"] = serve_df["Day"].replace(["Friday"],"FRI")
serve_df["Gender"] = serve_df["Gender"].replace(["Mal"],"Male")
serve_df["Gender"] = serve_df["Gender"].replace(["M"],"Male")
serve_df["Gender"] = serve_df["Gender"].replace(["F"],"Female")
serve_df["Gender"] = serve_df["Gender"].replace(["Fe"],"Female")

serve_df.Gender.unique()

array(['Female', 'Male'], dtype=object)

In [74]:
#cleaning the Smoker column
serve_df.Smoker.unique()

array(['No', 'N', nan, 'Yes', 'Y', 's'], dtype=object)

In [75]:
serve_df["Smoker"] = serve_df["Smoker"].replace(["Y"],"Yes")
serve_df["Smoker"] = serve_df["Smoker"].replace(["N"],"No")
serve_df["Smoker"] = serve_df["Smoker"].replace(["s"],np.NaN)

serve_df.Smoker.unique()

array(['No', nan, 'Yes'], dtype=object)

In [76]:
#cleaning the time column
serve_df.Time.unique()

array(['Dinner', 'Lunch', 'LD', 'L', 'Di', nan, 'Diner', 'D'],
      dtype=object)

In [77]:
serve_df["Time"] = serve_df["Time"].replace(["Di"],"Dinner")
serve_df["Time"] = serve_df["Time"].replace(["Diner"],"Dinner")
serve_df["Time"] = serve_df["Time"].replace(["D"],"Dinner")
serve_df["Time"] = serve_df["Time"].replace(["L"],"Lunch")
serve_df["Time"] = serve_df["Time"].replace(["LD"],np.NaN)

serve_df.Time.unique()

array(['Dinner', 'Lunch', nan], dtype=object)

In [78]:
#cleaning the Partysize column
serve_df.Partysize.unique()


array([ 2. ,  3. ,  4. ,  nan,  1. , 26. ,  6. ,  5. , 22. ,  0.2, 12. ,
       -2. ,  0. , 38. , 29. , 45. ])

In [79]:
#find the index of 0.2 in partysize


serve_df[serve_df['Partysize'] == 0.2].index



Index([176], dtype='int64')

In [80]:
#if partysize is less than 1 then change it to np.NaN
serve_df.loc[serve_df['Partysize'] < 1, 'Partysize'] = np.NaN

serve_df.Partysize.unique()

array([ 2.,  3.,  4., nan,  1., 26.,  6.,  5., 22., 12., 38., 29., 45.])

In [81]:
#from amount column replace the non float numbers with np.NaN
serve_df['Amount'] = pd.to_numeric(serve_df['Amount'], errors='coerce')
serve_df.Amount.unique()

array([ 16.99,  10.34,  21.01,  23.68,  24.59,  25.29,   8.77,  26.88,
        15.04,  14.78,  10.27,  35.26,  15.42,  18.43,  14.83,  21.58,
        10.33,  16.29,  16.97,  20.65,  17.92,  20.29,  15.77,  39.42,
        19.82,  17.81,  13.37,  12.69,  21.7 ,  19.65,   9.55,  18.35,
        15.06,  20.69,  17.78,  24.06,  16.31,  16.93,  18.69,  31.27,
        16.04,  17.46,  13.94,   9.68,  30.4 ,  18.29,  22.23,  32.4 ,
        28.55,  18.04,  12.54,  10.29,  34.81,   9.94,  25.56,  19.49,
        38.01,  26.41,  11.24,  48.27,  13.81,  11.02,  17.59,  20.08,
        16.45,   3.07,  20.23,  15.01,  12.02,  17.07,  26.86,  25.28,
        14.73,  10.51,  27.2 ,  22.76,  17.29,  19.44,  16.66,  10.07,
        32.68,  15.98,  34.83,  13.03,  18.28,  24.71,  21.16,  28.97,
        22.49,   5.75,  16.32,  22.75,  40.17,  27.28,  12.03,  12.46,
        11.35,  15.38,  44.3 ,  22.42,  20.92,  15.36,  20.49,  25.21,
        18.24,  14.31,  14.  ,   7.25,  38.07,  23.95,  25.71,  17.31,
      

In [82]:
#export the cleaned data to serve_cleaned.csv
serve_df.to_csv('serve_cleaned.csv', encoding='utf-8', index=False)